### Numpy

In [2]:
import numpy as np 


In [3]:
## create Array 
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
print(arr1.shape)

(5,)


In [ ]:
arr2=np.array([1,2,3,4,5]).reshape(1,5) ## 1 row and 5 columns
arr2

array([[1, 2, 3, 4, 5]])

In [ ]:
##2D Array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
### identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
### Attribute of Numpy Array
arr=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print("Array:\n" ,arr)
print("Shape:",arr.shape)
print("Number Of dimensions:",arr.ndim)
print("size(number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3 4 5]
 [2 3 4 5 6]]
Shape: (2, 5)
Number Of dimensions: 2
size(number of elements): 10
Data type: int32
Item size (in bytes): 4


In [18]:
### numpy vectorized Opreation 
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### element wise addition 
print("Addition:" , arr1+arr2)

### element wise substraction 
print("substraction:" , arr1-arr2)

### element wise multiplication 
print("substraction:" , arr1*arr2)

### element wise division 
print("division:" , arr1/arr2)

Addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
substraction: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [19]:
### Universal Function 
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

###Exponential
print(np.exp(arr))

##sine 
print(np.sin(arr))

### natural log 
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [21]:
## Array sclicing and Indexing 
arr=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
print("Array:\n" ,arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr[0][0]

1

In [24]:
arr[0][0] ### row - column

1

In [ ]:
arr[1:,2:] ### row and column 

array([[ 7,  8],
       [11, 12]])

In [27]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [28]:
print(arr[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
print(arr[0:2,1:])

[[2 3 4]
 [6 7 8]]


In [31]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [32]:
### Modify Array Elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [33]:
arr[1:]
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [34]:
##### statistical concept - normalization 
### to have a mean of 0 and std of 1 

data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)


normalized_data=(data-mean)/std_dev
print("Normalized Data :",normalized_data)

Normalized Data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [35]:
### mean meadian std var 
data=np.array([1,2,3,4,5,6,7,8,9,10])
mean=np.mean(data)
median=np.median(data)
std=np.std(data)
var=np.var(data)

print("Mean:",mean)
print("Median:",median)
print("Std",std)
print("Variance",var)

Mean: 5.5
Median: 5.5
Std 2.8722813232690143
Variance 8.25


In [36]:
### logical opreation 

data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
data[data>5] ## with indexing

array([ 6,  7,  8,  9, 10])

In [39]:
data[(data>=5)&(data<=8)]

array([5, 6, 7, 8])